### ISSUE TITLE
cell-status shouldn't need root access

### ISSUE THREAD

**Issue by slords** [freddenis/oracle-scripts#8]
You should be able to get the cell addresses the same way you do for exa-racklayout.  With this information you can login to each cell as celladmin (or cellmonitor) and query the same information.  This removes the need to login as root.

**Comment by freddenis** [comment]
Whether it should or should not need root access is moot and mainly depends on the client configuration. It should nevertheless offer the possibility of using root or any other user (source and target user) I do agree on that.
This script is not released yet, I am still working on it and will implement this in a near future. FYI, I consider a script "released" when I publish it on https://unknowndba.blogspot.com/.
Keep you updated though.

**Comment by freddenis** [comment]
Could you test it now ?

- It connects to the cells as root by default but you can change this using -u <user>
- If a non root user executes cell-status.sh, it looks into databasemachine.xml to find the cells to connect to instead of ibhosts
- You can use -c <cell_group> to specify a cell_group file

Let me know, thanks

**Comment by slords** [comment]
It appears to work great.  Would it be possible to default to cellmonitor if not running as root?

**Comment by freddenis** [comment]
Done !

**Comment by slords** [comment]
Confirmed.
